version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app/v1:/var/www/html
    command: bash -c "composer install && apache2-foreground"